"""empty message

Revision ID: 213c7a19724a
Revises: 3042e96815cc
Create Date: 2025-04-10 15:22:33.066423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '213c7a19724a'
down_revision: Union[str, None] = '3042e96815cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE secrets
        ALTER COLUMN secret_key
        TYPE UUID USING secret_key::uuid;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE secrets
        ALTER COLUMN secret_key
        TYPE TEXT USING secret_key::text;
    """)
    # ### end Alembic commands ###
