"""empty message

Revision ID: 3042e96815cc
Revises: a23cd266e17a
Create Date: 2025-04-10 14:59:52.880084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3042e96815cc'
down_revision: Union[str, None] = 'a23cd266e17a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('secrets_passphrase_key', 'secrets', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('secrets_passphrase_key', 'secrets', ['passphrase'])
    # ### end Alembic commands ###
