"""empty message

Revision ID: a23cd266e17a
Revises: e065a6da9db2
Create Date: 2025-04-10 14:33:43.201853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a23cd266e17a'
down_revision: Union[str, None] = 'e065a6da9db2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
        ALTER TABLE secrets
        ALTER COLUMN secret
        TYPE BYTEA USING secret::BYTEA;
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('secrets', 'secret',
               existing_type=sa.VARCHAR(),
               type_=sa.LargeBinary(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("""
        ALTER TABLE secrets
        ALTER COLUMN secret
        TYPE TEXT USING secret::TEXT;
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('secrets', 'secret',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
